inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 150

Lint/RequireRangeParentheses: 
  # new in 1.32 
  Enabled: true 

Naming/PredicateName:
  Enabled: false

Style/EmptyHeredoc: 
  # new in 1.32 
  Enabled: true

Style/MagicCommentFormat: 
  # new in 1.35 
  Enabled: true

Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true

Lint/UselessRescue: # new in 1.43
  Enabled: true

Style/ArrayIntersect: # new in 1.40
  Enabled: true

Style/ComparableClamp: # new in 1.44
  Enabled: true
  
Style/SingleLineMethods:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Lint/Debugger:
  DebuggerMethods:
    Capybara:
      "page.save_and_open_screenshot": ~

Naming/InclusiveLanguage:
  Enabled: false